import Head from "next/head";
import st from "../../styles/feedback.module.css"


export default function Feedback() {
  return (
    <>
      <Head>
        <title>Create Feedback Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={st.formWrapper}>
        <form className={st.myForm} action="/">
          <div className={st.formInner}>
            <h1>Send Me A Message</h1>
            <input type="text" placeholder="First Name" />
            <input type="text" placeholder="Last Name"  />
            <input type="email" placeholder="Email" />
            <textarea placeholder="Message..." rows="10" ></textarea>
            <button className={st.btn} type="submit" href="/fbform">
              Submit
            </button>
          </div>
        </form>
      </div>
    </>
  );
}