import { Button, Textarea, Select, Box, Link, FormControl, FormLabel, Input, FormHelperText, Heading, RadioGroup, HStack, Radio, Divider } from "@chakra-ui/react";
import Layout from "../../components/layout";
import { useState } from "react";

export default function Feedback() {

  const [input, setInput] = useState('');
  const handleEmailInput = (e) => setInput(e.target.value);
  const isError = input === '';

  return (
    <Layout>
      <Box as='Head'>
        <title>Create Feedback Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <Link rel="icon" href="/favicon.ico" />
      </Box>
      <Box as="div">
            <Heading as='h1' p='20px' color='whiteAlpha.900'>Send Me A Message</Heading>
          <FormControl p='20px' boxShadow='2xl' color='blackAlpha.700'>
            <FormLabel paddingTop='10px'>First Name</FormLabel>
            <Input type="text"/>
        
            <FormLabel paddingTop='10px'>Last Name</FormLabel>
            <Input type="text"/>

            <FormLabel paddingTop='10px'>Email</FormLabel>
            <Input type="email" value={input} onChange={handleEmailInput}/>
            {!isError ? (
              <FormHelperText>We'll never share your email</FormHelperText>
            ) : (
              <FormHelperText>Please enter your email</FormHelperText>
            )}

            <FormLabel as='legend' paddingTop='10px'>
              Gender
            </FormLabel>
            <RadioGroup defaultValue="Male">
              <HStack spacing='20px'>
                <Radio value='Male'>Male</Radio>
                <Radio value='Female'>Female</Radio>
              </HStack>
            </RadioGroup>

            <FormLabel paddingTop='10px'>Country</FormLabel>
            <Select placeholder="Select Country">
              <option>Australia</option>
              <option>Argentina</option>
              <option>China</option>
              <option>Hong Kong</option>
              <option>Japan</option>
              <option>Singapore</option>
              <option>South Korea</option>
              <option>United States</option>

            </Select>
            <Divider p='10px' />
            <Textarea placeholder='Enter your message here...' />
            <Divider orientation="vertical" p='10px' />
            <Button colorScheme="teal" type="submit" href="/">
              Submit
            </Button>
        </FormControl>
      </Box>
    </Layout>
  );
}